# Permalinks
permalink:           pretty

# Setup
title:               Larry's blog
tagline:             Larry's data science blog
url:                 http://lfiner.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Larry
  url:               https://lfiner.github.io
  email:             lfiner@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/lfiner

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
